```
docker secret create password db/mypassword
docker image build -t myapi:demo api
docker stack deploy -c docker-compose.yaml demo
```

 - http://localhost:8080/demo/price?name=widget : our API endpoint. `name` can be `widget` or `sprocket`
 - http://localhost:8080/swagger-ui.html : autogenerated API docs
 - http://localhost:8081/ : database admin interface
